repos:
  - repo: local
    hooks:
      # General checks
      - name: Prevent committing to main
        id: no-commit-to-branch
        language: system
        entry: no-commit-to-branch
        args: [--branch, main]
        pass_filenames: false
      - name: Make sure files end with a newline character
        id: end-of-file-fixer
        language: system
        entry: end-of-file-fixer
        types: [text]
      - name: Remove trailing whitespace
        id: trailing-whitespace-fixer
        language: system
        entry: trailing-whitespace-fixer
        types: [text]
      - name: Check for files that would conflict on case-insensitive filesystem
        id: check-case-conflict
        language: system
        entry: check-case-conflict
      - name: Check for merge conflicts
        id: check-merge-conflict
        language: system
        entry: check-merge-conflict
        types: [text]
      - name: Check executable files have a shebang
        id: check-executables-have-shebangs
        language: system
        entry: check-executables-have-shebangs
        types: [executable]
      - name: Check scripts with a shebang are executable
        id: check-shebang-scripts-are-executable
        language: system
        entry: check-shebang-scripts-are-executable
        types: [text]
      - name: Don't allow adding large files
        id: check-added-large-files
        language: system
        entry: check-added-large-files

      # Gleam
      - name: Format Gleam files
        id: gleam-format
        language: system
        entry: gleam format
        types: [gleam]
        pass_filenames: false
      - name: Check Gleam files
        id: gleam-check
        language: system
        entry: gleam check
        types: [gleam]
        pass_filenames: false
      - name: Run gleam2nix
        id: gleam2nix
        language: system
        entry: gleam2nix
        always_run: true
        pass_filenames: false

      # JSON
      - name: Format JSON files
        id: json-format
        language: system
        entry: prettier --write
        types: [json]

      # YAML
      - name: Format YAML files
        id: yaml-format
        language: system
        entry: prettier --write
        types: [yaml]

      # TOML
      - name: Sort TOML files
        id: toml-sort
        language: system
        entry: toml-sort --in-place --all
        types: [toml]

      # Markdown
      - name: Format markdown files
        id: markdown-format
        language: system
        entry: prettier --write
        types: [markdown]
      - name: Lint markdown files
        id: markdown-lint
        language: system
        entry: markdownlint-cli2
        args: [--config, .markdownlint.json]
        types: [markdown]

      # GitHub Actions
      - name: Validate GitHub Actions workflow files
        id: github-workflows-check
        language: system
        entry: zizmor --pedantic
        types: [yaml]
        files: ^.github/workflows/
      - name: Ratchet
        id: ratchet
        language: system
        entry: ratchet check
        types: [yaml]
        files: ^.github/workflows/

      # Nix
      - name: Format Nix files
        id: nix-format
        language: system
        entry: nixfmt
        types: [nix]
      - name: Lint Nix files
        id: deadnix
        language: system
        entry: deadnix
        types: [nix]

      # Just
      - name: Format Just files
        id: just-format
        language: system
        entry: just --unstable --fmt
        types: [text]
        files: ^Justfile$
        pass_filenames: false

      # Keep sorted
      - name: Keep sorted
        id: keep-sorted
        language: system
        entry: keep-sorted
        types: [text]

      # Typos
      - name: Check typos
        id: typos
        language: system
        entry: typos
        types: [text]
