description = "A simple tool to format TSV files"
licences = ["GPL-3.0-only"]
name = "tsvfmt"
repository = {repo = "tsvfmt", type = "github", user = "Hasnep"}
version = "2.0.0"

[dependencies]
argv = ">= 1.0.2 and < 2.0.0"
clip = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gleave = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
stdin = ">= 2.0.2 and < 3.0.0"
string_width = ">= 3.3.1 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
